# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Pack
      run: dotnet pack --no-build --output nupkgs
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    - name: Publish
      run: dotnet nuget push "nupkgs/**/*.nupkg" --source "https://nuget.pkg.github.com/hansei-hanum/index.json" --api-key ${{ secrets.NUGET_AUTH_TOKEN }}
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
